#########################################################################
# Title:         Saltbox: Radarr | Post-Install Tasks                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/saltyorg/Saltbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config file to be created
  ansible.builtin.wait_for:
    path: "{{ radarr_paths_config_location }}"
    state: present

- name: Post-Install | Update ports in '{{ radarr_paths_config_location | basename }}'
  import_tasks: update_ports.yml

- name: Post-Install | Install requirements for MED scripts
  ansible.builtin.shell: >
       docker exec {{ radarr_docker_container }} bash -c
       "cd /scripts/movie_extra_downloader/ && apk add py3-pip ffmpeg && pip3 install -r requirements.txt"
